import Placeholder from "../../../../public/Placeholder2.png";
export const MOCK_DEVSKOLAR_PROCESS = [
  {
    processStep: "Register",
    processImage: Placeholder,
    processText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport incididunt ut.",
  },
  {
    processStep: "Assessment",
    processImage: Placeholder,
    processText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport incididunt ut.",
  },
  {
    processStep: "Interview",
    processImage: Placeholder,
    processText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport incididunt ut.",
  },
  {
    processStep: "Announcement",
    processImage: Placeholder,
    processText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temport incididunt ut.",
  },
];
